### ISSUE TITLE
some questions about fid

### ISSUE THREAD

**Issue by dongguanting** [facebookresearch/UniK-QA#1]
When I used the FID checkpoint, I found that many parameters could not be loaded, and the accuracy rate was very low. I found that the oldest version of fid was also submitted in 2021.4, and this version also did not match. I can not find 2020 late version of FID，could you release any code that reproduced FID at that time？

**Comment by ccsasuke** [comment]
Hi @dongguanting, I recovered an older version of FiD and pushed that to a separate branch of the FiD repo: https://github.com/facebookresearch/FiD/tree/snapshot_nov_2020

**Comment by dongguanting** [comment]
Hello@ccsasuke，thank you for your reply. I still have a simple question.  What do “condensed.stagg.neighborhoods”  and ”condensed_hyper.stagg.neighborhoods“ represent respectively? I could not find how to get these two kinds of freebase triples in your article. I guess it may be your handling of complex relationships. Could you explain their role and the process of generating them？

**Comment by ccsasuke** [comment]
> Hello@ccsasuke，thank you for your reply. I still have a simple question. What do “condensed.stagg.neighborhoods” and ”condensed_hyper.stagg.neighborhoods“ represent respectively? I could not find how to get these two kinds of freebase triples in your article. I guess it may be your handling of complex relationships. Could you explain their role and the process of generating them？

These relations are the "n-ary relations" mentioned in the paper (Section 3.2). (We used to call them hyper-relations in the code.) In the code, we experimented with two ways of representing these n-ary relations, namely "condensed" and "condensed_hyper". The "condensed_hyper" representation is the final approach we took and the one described in the paper (Figure 2). The "condensed" representation would convert one "n-ary relation" into `n` binary relations, by connecting individual subject and objects.
For instance, the first example in Figure 2 would be converted to two sentences under the "condensed" representation: `Natalie Portman performance film Star Wars Episode I.` and `Natalie Portman performance character Padmé Amidala.`

**Comment by dongguanting** [comment]
Hello @ccsasuke, I have reproduced your code, but the result of webqsp is about 78. I think the possible reason is the DPR part. Because the embedding data is too large, it is difficult for me to download, so I directly load NQ single checkpoint to encode according to the code reproduction process，and DPR accuracy is about 94.7. I wonder if you can open source your DPR checkpoint? I really appreciate it!

**Comment by ccsasuke** [comment]
Hi @dongguanting, glad to hear that you were able to reproduce our results. Our retrieval accuracy is shown below.
<img width="622" alt="image" src="https://user-images.githubusercontent.com/1481766/209861289-b02323ae-14e0-4604-bf93-95378450f648.png">

Unfortunately the original DPR checkpoint had been purged from our server and we can no longer access it.
